backend:
  name: git-gateway
  repo: jesuscopado/neuronhub-gatsby
  branch: master

local_backend: true # Optional if you want to use the local proxy mode

publish_mode: editorial_workflow
media_folder: media    # I'm not using these default media directories at the moment.
public_folder: /media

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    delete: true
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "images"
    public_folder: "./images"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Hero", name: "hero", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }